server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql:///interview?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  #给包下的实体类生成默认别名
  type-aliases-package: org.java.entity
  #加载配置文件
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    org:
      java:
        dao: debug